Repository thoth-station/graph-refresh-job, pull requests merged in 2018-08, with the labels that each got.

#59 Add metadata to job template
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#62 Automatic update of dependency thoth-storages from 0.1.1 to 0.2.0
  Pipfile.lock
Labels: bot

#63 Automatic update of dependency thoth-storages from 0.2.0 to 0.3.0
  Pipfile.lock
Labels: bot

#65 Automatic update of dependency thoth-storages from 0.4.0 to 0.5.0
  Pipfile.lock
Labels: bot

#61 Decrease cronjob run
  openshift/cronJob-template.yaml
Labels: size/XS

#67 Automatic update of dependency thoth-storages from 0.5.0 to 0.5.1
  Pipfile.lock
Labels: bot

#60 Use OpenShift object from thoth-common
  Pipfile
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/L, size/M

#68 Automatic update of dependency thoth-common from 0.2.2 to 0.2.3
  Pipfile.lock
Labels: bot

#69 Automatic update of dependency thoth-common from 0.2.3 to 0.2.4
  Pipfile.lock
Labels: bot

#70 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot

#66 Debug mode is not hardcoded
  app.py
Labels: approved, size/XS
