Repository thoth-station/graph-refresh-job, pull requests merged in 2018-04, with the labels that each got.

#1 Initial implementation
  Pipfile
  Pipfile.lock
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
Labels: approved

#2 Propagate arguments for s2i
  openshift/buildConfig-template.yaml
Labels: approved

#6 adding the OWNERS file
  OWNERS
Labels: approved

#8 Separate imagestreams
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M

#10 Make cronjob runnable again
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/S

#12 License and license headers
  LICENSE
  app.py
Labels: approved, size/XL

#13 using MIDDLETIER now all over the place
  openshift/cronJob-template.yaml
Labels: approved

#14 added KUBERNETES_ to the ENV
  openshift/cronJob-template.yaml
Labels: approved, lgtm, size/XS

#18 added git commit hash to version output
  app.py
Labels: approved, size/M

#19 Omit non-int division check
  app.py
Labels: approved, size/XS

#21 Improve logging
  app.py
Labels: size/XS

#23 Increase duration of solver so it does not get killed too soon
  app.py
Labels: approved
