Repository thoth-station/graph-refresh-job, pull requests merged in 2018-07, with the labels that each got.

#39 Use service account token function from thoth-common
  app.py
Labels: approved, size/S

#41 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: approved, bot

#43 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#46 Initial dependency lock
  Pipfile.lock
Labels: bot

#47 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#48 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#49 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#50 Automatic update of dependency thoth-storages from 0.0.33 to 0.1.0
  Pipfile.lock
Labels: bot

#53 Run solver only if there are some packages
  app.py
Labels: approved

#54 Automatic update of dependency thoth-storages from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#56 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot
