Repository thoth-station/graph-refresh-job, pull requests merged in 2018-10, with the labels that each got.

#90 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#91 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#93 Automatic update of dependency thoth-common from 0.3.9 to 0.3.10
  Pipfile.lock
Labels: bot

#94 Automatic update of dependency thoth-common from 0.3.10 to 0.3.11
  Pipfile.lock
Labels: bot

#95 Automatic update of dependency thoth-storages from 0.5.2 to 0.5.3
  Pipfile.lock
Labels: bot

#96 Automatic update of dependency thoth-storages from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#97 added SENTRY_DSN envvar and removed JANUSGRAPH
  openshift/cronJob-template.yaml
Labels: approved, size/L

#103 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#102 sending some metrics to prometheus pushgateway
  .coafile
  .zuul.yaml
  Pipfile
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L, size/M

#104 Automatic update of dependency thoth-storages from 0.5.4 to 0.6.0
  Pipfile.lock
Labels: bot

#105 Stop eagerly after N solvers being scheduled
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/S

#106 Automatic update of dependency thoth-common from 0.3.12 to 0.3.13
  Pipfile.lock
Labels: bot

#107 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#108 No need to have new line to delimit a single package request
  app.py
Labels: approved, size/S

#110 Report any issues when scheduling solvers
  app.py
Labels: approved, size/S

#111 Automatic update of dependency thoth-common from 0.3.14 to 0.3.15
  Pipfile.lock
Labels: bot

#114 Automatic update of dependency thoth-storages from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot
