Repository thoth-station/graph-refresh-job, pull requests merged in 2018-11, with the labels that each got.

#117 Rename pod id to analysis id
  app.py
Labels: approved, size/XS

#118 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  Pipfile.lock
Labels: bot

#120 Fix log message
  app.py
Labels: approved, size/XS

#121 Automatic update of dependency thoth-storages from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: bot

#122 Automatic update of dependency thoth-storages from 0.7.3 to 0.7.4
  Pipfile.lock
Labels: bot

#123 added detailed version string
  app.py
Labels: approved, size/S

#125 Automatic update of dependency thoth-storages from 0.7.4 to 0.7.5
  Pipfile.lock
Labels: bot

#126 Automatic update of dependency thoth-storages from 0.7.5 to 0.7.6
  Pipfile.lock
Labels: bot

#124 added _info metric
  app.py
Labels: size/XS

#130 Automatic update of dependency thoth-common from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#131 Automatic update of dependency thoth-common from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#132 Automatic update of dependency thoth-common from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#136 Automatic update of dependency thoth-common from 0.4.3 to 0.4.4
  Pipfile.lock
Labels: bot

#143 Automatic update of dependency thoth-common from 0.4.4 to 0.4.5
  Pipfile.lock
Labels: bot

#148 Propagate index urls to solver runs
  app.py
Labels: approved, size/XS

#151 Automatic update of dependency thoth-storages from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot

#152 Automatic update of dependency thoth-common from 0.4.5 to 0.4.6
  Pipfile.lock
Labels: bot
