Repository thoth-station/graph-refresh-job, pull requests merged in 2019-11, with the labels that each got.

#302 Increase eager stop to 200 by default
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#303 Stop using starting deadline seconds
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#304 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#305 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#306 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#307 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#308 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#309 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#310 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.21
  Pipfile.lock
Labels: bot, size/S

#311 Automatic update of dependency thoth-storages from 0.19.21 to 0.19.22
  Pipfile.lock
Labels: bot, size/XS

#312 Add liveness probe
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#313 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#314 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#315 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#316 Automatic update of dependency thoth-common from 0.9.17 to 0.9.18
  Pipfile.lock
Labels: bot, size/M

#318 Automatic update of dependency thoth-common from 0.9.18 to 0.9.19
  Pipfile.lock
Labels: bot, size/M

#317 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/XS
