Repository thoth-station/graph-refresh-job, pull requests merged in 2019-08, with the labels that each got.

#236 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#237 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#238 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#239 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#241 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#242 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#243 Fix method name - the name has changed
  app.py
Labels: size/XS

#244 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XL

#247 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#245 Add missing deployment name for Sentry reports
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#249 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#250 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#251 Added config
  .thoth.yaml
Labels: approved, size/S

#248 WIP Add graph package analyzer refresh job
  app.py
Labels: approved, size/M

#253 Fix invalid metric label
  app.py
Labels: approved, size/XS

#255 Registry support for the cronjob image
  openshift/cronJob-template.yaml
Labels: approved, size/XS
