Repository thoth-station/graph-refresh-job, pull requests merged in 2019-01, with the labels that each got.

#159 Propagate subgraph-check api on graph refresh
  app.py
  openshift/cronJob-template.yaml
Labels: size/L

#161 Schedule solver instead of directly running it
  app.py
Labels: size/XS

#162 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
