Repository thoth-station/graph-refresh-job, pull requests merged in 2019-12, with the labels that each got.

#319 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#320 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#321 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/S

#322 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/S

#323 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#324 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#326 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M

#327 Shuffle not to be dependent on relative solver ordering
  app.py
Labels: approved, size/XS
