Repository thoth-station/graph-refresh-job, pull requests merged in 2019-06, with the labels that each got.

#198 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#199 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#200 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#202 Update zuul pipeline to use the new version trigger build job
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#206 Fix error when serializing parameters to JSON
  app.py
Labels: approved, size/XS

#209 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#211 Remove scheduling of dependent packages
  app.py
Labels: approved, size/S

#208 Standardize environment variables
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#205 Increase resources needed for a job run
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#212 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#203 Configure starting deadline seconds to large number
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#213 Schedule solvers based depending on packages which were not analyzed by these solvers
  app.py
Labels: approved, size/M

#214 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#216 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#215 Provide sane defaults and document job's behaviour
  README.rst
  app.py
Labels: size/M

#217 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot
