Repository thoth-station/graph-refresh-job, pull requests merged in 2019-09, with the labels that each got.

#261 Add package analyzer to the description
  README.rst
Labels: size/XS

#262 WIP Add ABI and templates for Package Analyzer
  README.rst
Labels: approved, size/XS

#263 Switch from Dgraph to PostgreSQL in deployment
  openshift/cronJob-template.yaml
Labels: approved, size/M

#264 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#254 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#265 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#266 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#267 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#256 Schedule solvers without a need to retrieve transitive dependencies
  app.py
Labels: approved, size/XS

#269 Fix iterating over unsolved Python packages
  app.py
Labels: approved, size/XS

#270 Fix iterating over versions - we have directly package_name, package_version
  app.py
Labels: approved, size/S

#271 Provide a way to turn off solver and package-analyzer scheduling
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/S

#272 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#273 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#275 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#276 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#277 use postgresql hostname from thoth configmap
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#278 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#279 Schedule solvers only for unsolved packages based on index
  app.py
Labels: approved, size/M

#280 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#281 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
