Repository thoth-station/graph-refresh-job, pull requests merged in 2019-02, with the labels that each got.

#164 Update year in sources
  app.py
Labels: size/XS

#167 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: bot

#168 Automatic update of dependency thoth-storages from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#170 Get unsolved packages depending on solver
  app.py
Labels: size/M
