Repository thoth-station/graph-refresh-job, pull requests merged in 2019-10, with the labels that each got.

#282 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#284 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#286 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#289 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#283 Remove subgraph checks
  app.py
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#285 Update function to retrieve unsolved packages and unanlyzed packages
  app.py
Labels: approved, size/L, size/M

#292 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#294 Fix return value when querying for un-analyzed Python packages
  app.py
Labels: approved, size/XS

#295 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/S

#296 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#297 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot

#299 Follow the convention
  app.py
Labels: approved, size/XS
