Repository thoth-station/graph-refresh-job, pull requests merged in 2020-10, with the labels that each got.

#520 Release of version 0.2.6
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#521 Messages sent metrics
  producer.py
Labels: approved, hacktoberfest-accepted, size/M

#523 Automatic update of dependency thoth-storages from 0.25.14 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/S

#525 Automatic update of dependency thoth-messaging from 0.7.9 to 0.7.11
  Pipfile.lock
Labels: approved, bot, size/S

#526 Release of version 0.2.7
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#530 Use topic_name
  producer.py
Labels: approved, size/XS

#533 Release of version 0.2.8
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#534 Locked thoth-messaging
  Pipfile
  Pipfile.lock
Labels: approved, size/L
