Repository thoth-station/graph-refresh-job, pull requests merged in 2020-07, with the labels that each got.

#418 Automatic update of dependency thoth-common from 0.13.8 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/L

#419 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#423 enable pre-commit support for the application
  .coafile
  .gitignore
  .pre-commit-config.yaml
  .thothTemplate.yaml
  CHANGELOG.md
  app.py
Labels: approved, size/L

#424 enable version to be managed at release
  app.py
Labels: approved, size/XS

#425 Remove result-api leftovers
  app.py
Labels: approved, size/XS

#426 migrate manifest for the application to config app
  .zuul.yaml
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#427 Drop package analyzer
  app.py
Labels: approved, size/M

#428 Schedule reverse solver workflow
  app.py
Labels: approved, size/M

#432 Release of version 0.1.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/L

#436 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#439 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/L
