Repository thoth-station/graph-refresh-job, pull requests merged in 2020-04, with the labels that each got.

#392 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#393 Shuffle solvers not to block, the relative solver positioning is not …
  app.py
Labels: approved, size/XS

#394 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#395 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#396 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#397 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#399 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/M

#400 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/S

#401 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#402 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#403 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#404 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
