Repository thoth-station/graph-refresh-job, pull requests merged in 2020-08, with the labels that each got.

#445 Automatic update of dependency thoth-common from 0.14.2 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/M

#446 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M

#447 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/XS

#444 Readme
  .gitignore
  README.rst
Labels: approved, size/XS

#451 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#452 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.1
  Pipfile.lock
Labels: approved, bot, size/M

#454 Release of version 0.1.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#456 parse_python_solver_name is function of thoth-common
  app.py
Labels: approved, size/XS

#448 Initial producer to replace app.py
  .env.template
  Pipfile
  Pipfile.lock
  app.py
  app.sh
  producer.py
  version.py
Labels: approved, size/XL

#458 Automatic update of dependency thoth-storages from 0.25.1 to 0.25.2
  Pipfile.lock
Labels: approved, bot, size/M

#459 Automatic update of dependency thoth-storages from 0.25.2 to 0.25.5
  Pipfile.lock
Labels: approved, bot, size/M

#460 Automatic update of dependency thoth-messaging from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: approved, bot, size/M
