Repository thoth-station/graph-refresh-job, pull requests merged in 2020-11, with the labels that each got.

#536 Automatic update of dependency thoth-common from 0.20.1 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/L

#537 Automatic update of dependency thoth-storages from 0.25.15 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/L

#540 Release of version 0.2.9
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#542 Updated pipfile lock with new storages
  Pipfile.lock
Labels: approved, size/L

#543 port to python 38
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#544 update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS
