Repository thoth-station/graph-refresh-job, pull requests merged in 2020-09, with the labels that each got.

#464 Automatic update of dependency thoth-common from 0.16.1 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/L

#465 Automatic update of dependency thoth-messaging from 0.6.5 to 0.7.0
  Pipfile.lock
Labels: approved, bot, size/L

#466 Added component name and service version to messages
  producer.py
Labels: approved, size/XS

#470 Automatic update of dependency thoth-common from 0.17.3 to 0.18.3
  Pipfile.lock
Labels: approved, bot, size/M

#471 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/M

#474 Add env var to configure number of messages sent
  producer.py
Labels: approved, size/XS

#475 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/XS

#476 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.2
  Pipfile.lock
Labels: approved, bot, size/XS

#477 Automatic update of dependency thoth-messaging from 0.7.0 to 0.7.2
  Pipfile.lock
Labels: approved, bot

#479 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.9
  Pipfile.lock
Labels: approved, bot

#478 Added producer logic for sending unanalyzed si packages
  producer.py
Labels: approved

#482 Release of version 0.2.0
  CHANGELOG.md
  version.py
Labels: approved, bot

#485 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#484 Add missing aicoe yaml
  .aicoe-ci.yaml
Labels: approved, size/S

#486 Automatic update of dependency thoth-messaging from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: approved, bot, size/S

#487 Automatic update of dependency thoth-messaging from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: approved, bot

#489 Automatic update of dependency thoth-messaging from 0.7.3 to 0.7.6
  Pipfile.lock
Labels: approved, bot, size/M

#491 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot

#495 Release of version 0.2.1
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#496 Added conditional env variables
  .env.template
  README.rst
  producer.py
Labels: approved, size/L

#499 Release of version 0.2.2
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#501 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: bot, size/M

#505 Release of version 0.2.3
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#506 Make app.sh executable
  app.sh
Labels: approved, size/XS

#508 Release of version 0.2.4
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#510 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/M

#511 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.8
  Pipfile.lock
Labels: approved, bot, size/M

#513 Release of version 0.2.5
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#515 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.14
  Pipfile.lock
Labels: approved, bot, size/S

#516 Automatic update of dependency thoth-messaging from 0.7.8 to 0.7.9
  Pipfile.lock
Labels: approved, bot, size/XS
