Repository thoth-station/graph-refresh-job, pull requests merged in 2020-01, with the labels that each got.

#328 Use arbitrary equality for solvers
  app.py
Labels: approved, size/XS

#329 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#330 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#332 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#334 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#333 Correctly handle eager stop for packages
  app.py
Labels: approved, size/XS

#331 Happy new year!
  app.py
Labels: size/XS

#335 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#336 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/M

#337 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#339 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#340 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#341 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#343 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#342 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#344 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#345 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/S

#346 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#347 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#348 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#349 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#350 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/XS

#351 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#352 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/M

#353 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#354 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/M

#355 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/S

#356 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#357 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#358 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#359 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/XS

#360 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#362 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#363 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/M
