Repository thoth-station/graph-refresh-job, pull requests merged in 2020-03, with the labels that each got.

#379 Add variables for solver workflows
  openshift/cronJob-template.yaml
Labels: approved, size/S

#380 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/M

#381 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/L

#382 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.4
  Pipfile.lock
Labels: bot

#383 Automatic update of dependency thoth-storages from 0.22.4 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#384 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#385 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#386 Automatic update of dependency thoth-common from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/M

#387 Automatic update of dependency thoth-common from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot, size/S

#388 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/XS

#389 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/S

#390 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M

#391 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M
