Repository thoth-station/graph-refresh-job, pull requests merged in 2020-02, with the labels that each got.

#364 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#365 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#366 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#367 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#369 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/S

#368 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#370 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/S

#371 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/XS

#372 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#373 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#374 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#375 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#376 Add environment variable to run solvers through Argo
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#377 Update version due to new variable for Argo
  openshift/cronJob-template.yaml
Labels: approved, size/XS

#378 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/M
