Repository thoth-station/graph-refresh-job, pull requests merged in 2021-01, with the labels that each got.

#545 Use deployment-name for metrics
  producer.py
Labels: approved, size/S

#548 update to latest messaging
  Pipfile
  Pipfile.lock
  app.sh
  producer.py
Labels: approved, do-not-merge/needs-rebase, size/L

#549 Adjust rebase error
  Pipfile.lock
Labels: approved, size/XS

#550 Add schema metric
  producer.py
Labels: approved, size/S

#553 add maintainer
  .thoth.yaml
Labels: size/XS

#558 Correct base image
  .aicoe-ci.yaml
Labels: approved, size/XS

#564 Relock pipfile for typing_extension issue fix
  Pipfile.lock
Labels: approved, size/M

#566 fix the pre-commit issue in producer.py
  producer.py
Labels: approved, size/M
